[features]
seeds = false
skip-lint = false
[programs.localnet]
gacha_marketplace = "DhzZ4J9xF7Q9ECsyuC8NL1Zy1XToLSkpUfhE7k57rYP1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tungleanh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
